networks:
  local:
    driver: bridge

services:
  nginx:
    container_name: nginx
    build:
      context: ./Nginx
      dockerfile: Dockerfile
      args:
        - ESUS_IFRAME_GITHUB=${ESUS_IFRAME_GITHUB}
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - pec
    networks:
      - local
  pec:
    container_name: pec
    platform: linux/amd64
    volumes:
      - /esus-data/opt:/opt/e-SUS
      - /esus-data/backups:/backups
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    build:
      context: ./Pec
      dockerfile: Dockerfile
      args:
        POSTGRES_HOST: ${POSTGRES_HOST}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ESUS_DOWNLOAD_VERSION_URL: ${ESUS_DOWNLOAD_VERSION_URL}
    environment:
      - TZ=America/Recife
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
    privileged: true
    stdin_open: true
    tty: true
    ports:
      - "8081:8080"
      - "8082:80"
      - "8083:443"
    depends_on:
      - db
    networks:
      - local
  db:
    container_name: db
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5433:5432" 
    volumes:
      - /esus-data/db:/var/lib/postgresql/data
    networks:
      - local
